version: 2
updates:
  # Project root
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"

  # NextJS Client
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  # tRPC API package
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/packages/api"
    schedule:
      interval: "weekly"

  # Auth package
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/packages/auth"
    schedule:
      interval: "weekly"

  # Prisma DB package
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/packages/db"
    schedule:
      interval: "weekly"

  # ESLint config package
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/packages/config/eslint"
    schedule:
      interval: "weekly"

  # Tailwind config package
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/packages/config/tailwind"
    schedule:
      interval: "weekly"
